/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeCloudModelMarketRouteImport } from './routes/home/cloud-model-market'
import { Route as HomeCloudAppMarketRouteImport } from './routes/home/cloud-app-market'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCloudModelMarketRoute = HomeCloudModelMarketRouteImport.update({
  id: '/cloud-model-market',
  path: '/cloud-model-market',
  getParentRoute: () => HomeRoute,
} as any)
const HomeCloudAppMarketRoute = HomeCloudAppMarketRouteImport.update({
  id: '/cloud-app-market',
  path: '/cloud-app-market',
  getParentRoute: () => HomeRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/cloud-app-market': typeof HomeCloudAppMarketRoute
  '/home/cloud-model-market': typeof HomeCloudModelMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/cloud-app-market': typeof HomeCloudAppMarketRoute
  '/home/cloud-model-market': typeof HomeCloudModelMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/cloud-app-market': typeof HomeCloudAppMarketRoute
  '/home/cloud-model-market': typeof HomeCloudModelMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/register'
    | '/home/cloud-app-market'
    | '/home/cloud-model-market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/register'
    | '/home/cloud-app-market'
    | '/home/cloud-model-market'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/auth/login'
    | '/auth/register'
    | '/home/cloud-app-market'
    | '/home/cloud-model-market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/cloud-model-market': {
      id: '/home/cloud-model-market'
      path: '/cloud-model-market'
      fullPath: '/home/cloud-model-market'
      preLoaderRoute: typeof HomeCloudModelMarketRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/cloud-app-market': {
      id: '/home/cloud-app-market'
      path: '/cloud-app-market'
      fullPath: '/home/cloud-app-market'
      preLoaderRoute: typeof HomeCloudAppMarketRouteImport
      parentRoute: typeof HomeRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeCloudAppMarketRoute: typeof HomeCloudAppMarketRoute
  HomeCloudModelMarketRoute: typeof HomeCloudModelMarketRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCloudAppMarketRoute: HomeCloudAppMarketRoute,
  HomeCloudModelMarketRoute: HomeCloudModelMarketRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
