/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeIndexBkRouteImport } from './routes/home/index-bk'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as HomeAppMarketIndexRouteImport } from './routes/home/app-market/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexBkRoute = HomeIndexBkRouteImport.update({
  id: '/home/index-bk',
  path: '/home/index-bk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAppMarketIndexRoute = HomeAppMarketIndexRouteImport.update({
  id: '/home/app-market/',
  path: '/home/app-market/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/index-bk': typeof HomeIndexBkRoute
  '/home': typeof HomeIndexRoute
  '/home/app-market': typeof HomeAppMarketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/index-bk': typeof HomeIndexBkRoute
  '/home': typeof HomeIndexRoute
  '/home/app-market': typeof HomeAppMarketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/home/index-bk': typeof HomeIndexBkRoute
  '/home/': typeof HomeIndexRoute
  '/home/app-market/': typeof HomeAppMarketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/home/index-bk'
    | '/home'
    | '/home/app-market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/home/index-bk'
    | '/home'
    | '/home/app-market'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/home/index-bk'
    | '/home/'
    | '/home/app-market/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  HomeIndexBkRoute: typeof HomeIndexBkRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAppMarketIndexRoute: typeof HomeAppMarketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/index-bk': {
      id: '/home/index-bk'
      path: '/home/index-bk'
      fullPath: '/home/index-bk'
      preLoaderRoute: typeof HomeIndexBkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/app-market/': {
      id: '/home/app-market/'
      path: '/home/app-market'
      fullPath: '/home/app-market'
      preLoaderRoute: typeof HomeAppMarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  HomeIndexBkRoute: HomeIndexBkRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeAppMarketIndexRoute: HomeAppMarketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
